# ░░░░░GOOSE UP░░░░░░░░░░░░░░░░░░░GOOSE UP░░░░░░░░░░░░░░
# ░░░THE REPOSITORY, FOLKS░░░░░░THE REPOSITORY, FOLKS░░░
# ░░░░░█▀▀▀█░░░░░░░░░░░░░░░░░░░░░░█▀▀▀█░░░░░░░░░░░░░░░░░
# ▄███▀░◐░░▌░░░░░░░░░░░░░░░░▄███▀░◐░░▌░░░░░░░░░░░░░░░░
# ░░░░▌░░░░░▐░░░░░░░░░░░░░░░░░░░░▌░░░░░▐░░░░░░░░░░░░░░░░
# ░░░░▐░░░░░▐░░░░░░░░░░░░░░░░░░░░▐░░░░░▐░░░░░░░░░░░░░░░░
# ░░░░▌░░░░░▐▄▄░░░░░░░░░░░░░░░░░░▌░░░░░▐▄▄░░░░░░░░░░░░░░
# ░░░░▌░░░░▄▀▒▒▀▀▀▀▄░░░░░░░░░░░░░▌░░░░▄▀▒▒▀▀▀▀▄░░░░░░░░░
# ░░░▐░░░░▐▒▒▒▒▒▒▒▒▀▀▄░░░░░░░░░░▐░░░░▐▒▒▒▒▒▒▒▒▀▀▄░░░░░░░
# ░░░▐░░░░▐▄▒▒▒▒▒▒▒▒▒▒▀▄░░░░░░░░▐░░░░▐▄▒▒▒▒▒▒▒▒▒▒▀▄░░░░░
# ░░░░▀▄░░░░▀▄▒▒▒▒▒▒▒▒▒▒▀▄░░░░░░░▀▄░░░░▀▄▒▒▒▒▒▒▒▒▒▒▀▄░░░
# ░░░░░░▀▄▄▄▄▄█▄▄▄▄▄▄▄▄▄▀▄░░░░░░░░░▀▄▄▄▄▄█▄▄▄▄▄▄▄▄▄▀▄░░░
# ░░░░░░░░░░░▌▌░▌▌░░░░░░░░░░░░░░░░░░░░░░▌▌░▌▌░░░░░░░░░░░
# ░░░░░░░░░░░▌▌░▌▌░░░░░░░░░░░░░░░░░░░░░░▌▌░▌▌░░░░░░░░░░░
# ░░░░░░░░░▄▄▌▌▄▌▌░░░░░░░░░░░░░░░░░░░░▄▄▌▌▄▌▌░░░░░░░░░░░

services:
#  moder-api:
#    build: .
#    ports:
#      - "8001:8001"
  telegram_bot:
    image: ghcr.io/labubu-team/labubu-tgbot:latest
    pull_policy: always
    environment:
      SERVICE_ACCOUNT_ID: ${SERVICE_ACCOUNT_ID:?SERVICE_ACCOUNT_ID is required}
      PUBLIC_KEY: ${PUBLIC_KEY:?PUBLIC_KEY is required}
      PRIVATE_KEY: ${PRIVATE_KEY:?PRIVATE_KEY is required}
      KEY_ID: ${KEY_ID:?KEY_ID is required}
      FOLDER_ID: ${FOLDER_ID:?FOLDER_ID is required}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN:?TELEGRAM_TOKEN is required}
    networks:
      - labubu_net
  rag:
    image: ghcr.io/labubu-team/labubu-rag:latest
    pull_policy: always
    networks:
      - labubu_net

networks:
  labubu_net:
    driver: bridge