name: Release Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push_tgbot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase owner
        id: repo
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build & push Telegram Bot image
        run: |
          REPO=ghcr.io/${{ steps.repo.outputs.owner_lc }}/labubu-tgbot
          docker build -f ./telegram_bot/Dockerfile -t $REPO:latest -t $REPO:${{ github.run_number }} .
          docker push $REPO:latest
          docker push $REPO:${{ github.run_number }}
    

      - name: Get Yandex Cloud IAM token
        id: get-iam-token
        uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
        with:
          yc-sa-id: ${{ secrets.SERVICE_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: iam
          password: ${{ steps.get-iam-token.outputs.token }}
      
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        run: |
          YC_REPO=cr.yandex/${{ secrets.CONTAINER_REPO }}/labubu-tgbot
          docker build -f ./telegram_bot/Dockerfile -t $YC_REPO:latest -t $YC_REPO:${{ github.run_number }} .
          docker push $YC_REPO:latest
          docker push $YC_REPO:${{ github.run_number }}

      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v4
        with:
          yc-sa-id: ${{ secrets.SA_ID }}
          container-name: tgbot
          folder-id: ${{ secrets.YC_FOLDER }}
          revision-service-account-id: ${{ secrets.SA_ID }}
          revision-cores: 1
          revision-memory: 1024Mb
          revision-core-fraction: 20
          revision-concurrency: 8
          revision-image-url: cr.yandex/${{ secrets.CONTAINER_REPO }}/labubu-tgbot:${{ github.run_number }}
          revision-execution-timeout: 10
          revision-secrets: |
            TELEGRAM_TOKEN=tg_api/latest/tg_token
            SERVICE_ACCOUNT_ID=SERVICE_ACCOUNT_ID/latest/SERVICE_ACCOUNT_ID


  build-and-push_rag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase owner
        id: repo
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build & push rag image
        run: |
          REPO=ghcr.io/${{ steps.repo.outputs.owner_lc }}/labubu-rag
          docker build -f ./rag/Dockerfile -t $REPO:latest -t $REPO:${{ github.run_number }} .
          docker push $REPO:latest
          docker push $REPO:${{ github.run_number }}

      - name: Get Yandex Cloud IAM token
        id: get-iam-token
        uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
        with:
          yc-sa-id: ${{ secrets.SERVICE_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: iam
          password: ${{ steps.get-iam-token.outputs.token }}
      
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        run: |
          YC_REPO=cr.yandex/${{ secrets.CONTAINER_REPO }}/labubu-rag
          docker build -f ./rag/Dockerfile -t $YC_REPO:latest -t $YC_REPO:${{ github.run_number }} .
          docker push $YC_REPO:latest
          docker push $YC_REPO:${{ github.run_number }}

      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v4
        with:
          yc-sa-id: ${{ secrets.SA_ID }}
          container-name: rag
          folder-id: ${{ secrets.YC_FOLDER }}
          revision-service-account-id: ${{ secrets.SA_ID }}
          revision-cores: 1
          revision-memory: 1024Mb
          revision-core-fraction: 100
          revision-concurrency: 8
          revision-image-url: cr.yandex/${{ secrets.CONTAINER_REPO }}/labubu-rag:${{ github.run_number }}
          revision-execution-timeout: 10
          revision-secrets: |
            TELEGRAM_TOKEN=tg_api/latest/tg_token
            SERVICE_ACCOUNT_ID=SERVICE_ACCOUNT_ID/latest/SERVICE_ACCOUNT_ID

  build-and-push_moderation_nlp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase owner
        id: repo
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build & push moderation_nlp image
        run: |
          REPO=ghcr.io/${{ steps.repo.outputs.owner_lc }}/labubu-moderation_nlp
          docker build -f ./moderation_nlp/Dockerfile -t $REPO:latest -t $REPO:${{ github.run_number }} .
          docker push $REPO:latest
          docker push $REPO:${{ github.run_number }}

      - name: Get Yandex Cloud IAM token
        id: get-iam-token
        uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
        with:
          yc-sa-id: ${{ secrets.SERVICE_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: iam
          password: ${{ steps.get-iam-token.outputs.token }}
      
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        run: |
          YC_REPO=cr.yandex/${{ secrets.CONTAINER_REPO }}/labubu-moderation_nlp
          docker build -f ./moderation_nlp/Dockerfile -t $YC_REPO:latest -t $YC_REPO:${{ github.run_number }} .
          docker push $YC_REPO:latest
          docker push $YC_REPO:${{ github.run_number }}

      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v4
        with:
          yc-sa-id: ${{ secrets.SA_ID }}
          container-name: moderation-nlp
          folder-id: ${{ secrets.YC_FOLDER }}
          revision-service-account-id: ${{ secrets.SA_ID }}
          revision-cores: 4
          revision-memory: 4096Mb
          revision-core-fraction: 100
          revision-concurrency: 8
          revision-image-url: cr.yandex/${{ secrets.CONTAINER_REPO }}/labubu-moderation-nlp:${{ github.run_number }}
          revision-execution-timeout: 10
          revision-secrets: |
            TELEGRAM_TOKEN=tg_api/latest/tg_token
            SERVICE_ACCOUNT_ID=SERVICE_ACCOUNT_ID/latest/SERVICE_ACCOUNT_ID

  build-and-push_moderation_regex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase owner
        id: repo
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build & push moderation_regex image
        run: |
          REPO=ghcr.io/${{ steps.repo.outputs.owner_lc }}/labubu-moderation_regex
          docker build -f ./moderation_regex/Dockerfile -t $REPO:latest -t $REPO:${{ github.run_number }} .
          docker push $REPO:latest
          docker push $REPO:${{ github.run_number }}

      - name: Get Yandex Cloud IAM token
        id: get-iam-token
        uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
        with:
          yc-sa-id: ${{ secrets.SERVICE_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: iam
          password: ${{ steps.get-iam-token.outputs.token }}
      
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        run: |
          YC_REPO=cr.yandex/${{ secrets.CONTAINER_REPO }}/labubu-moderation_regex
          docker build -f ./moderation_regex/Dockerfile -t $YC_REPO:latest -t $YC_REPO:${{ github.run_number }} .
          docker push $YC_REPO:latest
          docker push $YC_REPO:${{ github.run_number }}

      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v4
        with:
          yc-sa-id: ${{ secrets.SA_ID }}
          container-name: moderation_regex
          folder-id: ${{ secrets.YC_FOLDER }}
          revision-service-account-id: ${{ secrets.SA_ID }}
          revision-cores: 1
          revision-memory: 2048Mb
          revision-core-fraction: 20
          revision-concurrency: 8
          revision-image-url: cr.yandex/${{ secrets.CONTAINER_REPO }}/labubu-moderation_regex:${{ github.run_number }}
          revision-execution-timeout: 10
          revision-secrets: |
            TELEGRAM_TOKEN=tg_api/latest/tg_token
            SERVICE_ACCOUNT_ID=SERVICE_ACCOUNT_ID/latest/SERVICE_ACCOUNT_ID
      

  build-and-push_llm-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase owner
        id: repo
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build & push LLM Agent GITHUB
        run: |
          REPO=ghcr.io/${{ steps.repo.outputs.owner_lc }}/llm_agent
          docker build -f ./llm_agent/Dockerfile -t $REPO:latest -t $REPO:${{ github.run_number }} .
          docker push $REPO:latest
          docker push $REPO:${{ github.run_number }}

      - name: Get Yandex Cloud IAM token
        id: get-iam-token
        uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
        with:
          yc-sa-id: ${{ secrets.SERVICE_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: iam
          password: ${{ steps.get-iam-token.outputs.token }}
      
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        run: |
          YC_REPO=cr.yandex/${{ secrets.CONTAINER_REPO }}/labubu-llm_agent
          docker build -f ./llm_agent/Dockerfile -t $YC_REPO:latest -t $YC_REPO:${{ github.run_number }} .
          docker push $YC_REPO:latest
          docker push $YC_REPO:${{ github.run_number }}

      # автоматический деплой пока что отсутствует, по причине того что все должно работать на видеокарте в НОДЕ

  
  build-and-push_orchestrator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase owner
        id: repo
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Build & push orchestrator GITHUB
        run: |
          REPO=ghcr.io/${{ steps.repo.outputs.owner_lc }}/orchestrator
          docker build -f ./orchestrator/Dockerfile -t $REPO:latest -t $REPO:${{ github.run_number }} .
          docker push $REPO:latest
          docker push $REPO:${{ github.run_number }}

      - name: Get Yandex Cloud IAM token
        id: get-iam-token
        uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
        with:
          yc-sa-id: ${{ secrets.SERVICE_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: iam
          password: ${{ steps.get-iam-token.outputs.token }}
      
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        run: |
          YC_REPO=cr.yandex/${{ secrets.CONTAINER_REPO }}/labubu-orchestrator
          docker build -f ./orchestrator/Dockerfile -t $YC_REPO:latest -t $YC_REPO:${{ github.run_number }} .
          docker push $YC_REPO:latest
          docker push $YC_REPO:${{ github.run_number }}

      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v4
        with:
          yc-sa-id: ${{ secrets.SA_ID }}
          container-name: orchestrator
          folder-id: ${{ secrets.YC_FOLDER }}
          revision-service-account-id: ${{ secrets.SA_ID }}
          revision-cores: 2
          revision-memory: 2048Mb
          revision-core-fraction: 50
          revision-concurrency: 8
          revision-image-url: cr.yandex/${{ secrets.CONTAINER_REPO }}/labubu-orchestrator:${{ github.run_number }}
          revision-execution-timeout: 10
          revision-secrets: |
            TELEGRAM_TOKEN=tg_api/latest/tg_token
            SERVICE_ACCOUNT_ID=SERVICE_ACCOUNT_ID/latest/SERVICE_ACCOUNT_ID